# Generated by Django 4.2.28 on 2026-02-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_carimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image_url',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonials/'),
        ),
    ]
