export const sampleCars = [
  {
    name: "BMW M5 Competition",
    brand: "BMW",
    model: "M5",
    year: 2023,
    price: 89500,
    mileage: "12,000 km",
    fuelType: "Petrol",
    imageUrl: "https://images.unsplash.com/photo-1764605206511-7a649d9df63b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsdXh1cnklMjBzZWRhbiUyMGJsYWNrfGVufDF8fHx8MTc3MDg0MDc1Nnww&ixlib=rb-4.1.0&q=80&w=1080",
    condition: "Certified Pre-Owned",
    description: "Powerful luxury sedan with twin-turbo V8 engine. Full service history and immaculate condition.",
    transmission: "Automatic",
    color: "Black",
  },
  {
    name: "Porsche 911 Carrera",
    brand: "Porsche",
    model: "911",
    year: 2024,
    price: 125000,
    mileage: "5,000 km",
    fuelType: "Petrol",
    imageUrl: "https://images.unsplash.com/photo-1618480483701-c31ac5590db4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcG9ydHMlMjBjYXIlMjBzaWRlJTIwdmlld3xlbnwxfHx8fDE3NzA3ODAwODl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    condition: "New",
    description: "Iconic sports car with legendary performance. Brand new with full warranty.",
    transmission: "Automatic",
    color: "Racing Yellow",
  },
  {
    name: "Range Rover Sport",
    brand: "Land Rover",
    model: "Range Rover Sport",
    year: 2023,
    price: 95000,
    mileage: "18,000 km",
    fuelType: "Diesel",
    imageUrl: "https://images.unsplash.com/photo-1728460593090-10055723ac39?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdXYlMjBjYXIlMjBtb3VudGFpbnxlbnwxfHx8fDE3NzA4NzcwOTV8MA&ixlib=rb-4.1.0&q=80&w=1080",
    condition: "Used",
    description: "Luxurious SUV with exceptional off-road capabilities. Perfect for both city and adventure.",
    transmission: "Automatic",
    color: "Silver",
  },
];

export const sampleTestimonials = [
  {
    customerName: "Sarah Johnson",
    carPurchased: "BMW M5 Competition",
    rating: 5,
    feedback: "Exceptional service from start to finish! The team was professional, knowledgeable, and helped me find my dream car. Highly recommend AutoElite!",
    imageUrl: "https://images.unsplash.com/photo-1629991787749-e2a79eea0471?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzbWlsaW5nJTIwY3VzdG9tZXIlMjBwb3J0cmFpdCUyMHByb2Zlc3Npb25hbHxlbnwxfHx8fDE3NzA4NzcwOTh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    purchaseDate: "2026-01-15",
  },
  {
    customerName: "Michael Chen",
    carPurchased: "Porsche 911 Carrera",
    rating: 5,
    feedback: "Best car buying experience ever! The financing options were flexible and the entire process was seamless. Love my new Porsche!",
    imageUrl: "https://images.unsplash.com/photo-1629991787749-e2a79eea0471?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzbWlsaW5nJTIwY3VzdG9tZXIlMjBwb3J0cmFpdCUyMHByb2Zlc3Npb25hbHxlbnwxfHx8fDE3NzA4NzcwOTh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    purchaseDate: "2026-01-28",
  },
  {
    customerName: "Emily Rodriguez",
    carPurchased: "Range Rover Sport",
    rating: 5,
    feedback: "Outstanding quality and service! The car was exactly as described and the team went above and beyond to ensure I was satisfied. Will definitely return for my next purchase!",
    imageUrl: "https://images.unsplash.com/photo-1629991787749-e2a79eea0471?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzbWlsaW5nJTIwY3VzdG9tZXIlMjBwb3J0cmFpdCUyMHByb2Zlc3Npb25hbHxlbnwxfHx8fDE3NzA4NzcwOTh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    purchaseDate: "2026-02-05",
  },
];

export const sampleSales = [
  {
    carBrand: "BMW",
    carName: "BMW M5 Competition",
    salePrice: 89500,
    profit: 12500,
    customerName: "Sarah Johnson",
    saleDate: "2026-01-15",
  },
  {
    carBrand: "Porsche",
    carName: "Porsche 911 Carrera",
    salePrice: 125000,
    profit: 18000,
    customerName: "Michael Chen",
    saleDate: "2026-01-28",
  },
  {
    carBrand: "Land Rover",
    carName: "Range Rover Sport",
    salePrice: 95000,
    profit: 15000,
    customerName: "Emily Rodriguez",
    saleDate: "2026-02-05",
  },
  {
    carBrand: "Mercedes",
    carName: "Mercedes-Benz S-Class",
    salePrice: 110000,
    profit: 16500,
    customerName: "David Park",
    saleDate: "2025-12-20",
  },
  {
    carBrand: "Audi",
    carName: "Audi RS6 Avant",
    salePrice: 95000,
    profit: 14000,
    customerName: "Lisa Anderson",
    saleDate: "2025-11-10",
  },
];
